name: SglPPow
version: "2.4"
license: "Artistic-2.0"
date: 2024-03-20
description: |
    Database of groups of prime-power order for some prime-powers

authors:
    - name: Michael Vaughan-Lee
      url: https://users.ox.ac.uk/~vlee
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick

maintainers:
    - name: Michael Vaughan-Lee
      url: https://users.ox.ac.uk/~vlee
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick

GAP: ">=4.7"

suggested-pkgs:
    - name: "LiePRing"
      version: ">=1.8"
      url: "https://gap-packages.github.io/liepring/"
    - name: "LieRing"
      version: ">=2.2"
      url: "https://gap-packages.github.io/liering/"

www: https://gap-packages.github.io/sglppow/
readme: README.md
packageinfo: https://gap-packages.github.io/sglppow/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/sglppow/releases/download/v2.4/sglppow-2.4.tar.gz

abstract: |

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    , , .
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>VE24</span>]   <b class='BibAuthor'>Vaughan-Lee, M. and Eick, B.</b>,
     <i class='BibTitle'>SglPPow, Database of groups of prime-power order for some prime-powers,
             Version 2.4</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/sglppow/">https://gap-packages.github.io/sglppow/</a></span>.
    </p>
    

bibtex: |
    @misc{ SglPPow,
      author =           {Vaughan\texttt{\symbol{45}}Lee, M. and Eick, B.},
      title =            {{SglPPow},       Database       of      groups      of
                          prime\texttt{\symbol{45}}power    order    for    some
                          prime\texttt{\symbol{45}}powers, {V}ersion 2.4},
      month =            {Mar},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href        {https://gap-packages.github.io/sglppow/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{sglppow/}}},
      keywords =         {; ;},
      printedkey =       {VE24}
    }

