name: SglPPow
version: 2.3
date: 2022-11-04
description: |
    Database of groups of prime-power order for some prime-powers

authors:
    - name: Michael Vaughan-Lee
      url: https://users.ox.ac.uk/~vlee
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick

maintainers:
    - name: Michael Vaughan-Lee
      url: https://users.ox.ac.uk/~vlee
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick

GAP: ">=4.7"

suggested-pkgs:
    - name: "LiePRing"
      version: ">=1.8"
      url: "https://gap-packages.github.io/liepring/"
    - name: "LieRing"
      version: ">=2.2"
      url: "https://gap-packages.github.io/liering/"

www: https://gap-packages.github.io/sglppow/
readme: README.md
packageinfo: https://gap-packages.github.io/sglppow/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/sglppow/releases/download/v2.3/sglppow-2.3.tar.gz

abstract: |

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
