# SglPPow, chapter 2
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("sglppow01.tst");

# doc/access.xml:33-42
gap> NumberSmallGroups(3^8);
1396077
gap> SmallGroup(3^8, 1000000);
<pc group of size 6561 with 8 generators>
gap> NumberSmallGroups(17^7);
5546909
gap> NumberSmallGroups(101^7);
32826263845

#
gap> STOP_TEST("sglppow01.tst", 1);
