#!/usr/bin/env python3
"""Encode pc group codes of the groups of order 3^8 for lib/3hoch8.

Usage: etc/encode-3hoch8.py <outdir> <codefile>...

Each <codefile> holds the codes of one rank/class layer as decimal integers
(any GAP list of them will do, including the files this script writes its
input from); the layer number is taken from the file name.  The output is
read by lib/3hoch8/decode.g.

A code, as built by CodePcgs and read back by RelatorsCode, is a bit mask of
the 35 possible relations of a pc presentation on 8 generators followed by
one tail per set bit, each tail an element of the group written base 3^8.
Since the tail of relation r lies in the subgroup generated by the later
generators, the whole code is equivalent to 84 exponents in 0..2 -- a fixed
layout, which is what makes two groups comparable.

Consecutive groups of a layer differ in 1.9 of those 84 exponents on average,
so a layer is stored as the exponents of its first group plus, per group, the
positions that change.  Every 256th group a checkpoint records the state, so
that a single group is reached without replaying the whole layer.
"""

import os
import re
import sys

P = 3
L = 8                              # generators
SIZE = P**L                        # 6561
NREL = (L-1) + L*(L-1)//2          # 7 powers, then the commutators [g_j,g_i]

# number of exponents of each relation: its tail lies in <g_{k+1},..,g_L>
NTRITS = [L-i for i in range(1, L)] + [L-j for i in range(1, L+1)
                                            for j in range(i+1, L+1)]
NPOS = sum(NTRITS)                 # 84

ALPHA = ''.join(chr(c) for c in range(0x28, 0x7F) if c != 0x5C)   # 86 symbols
KMAX = 5                           # changes covered by a header symbol
HDR = [0] + [sum(1 << i for i in range(1, k+1)) for k in range(1, KMAX+1)]
ESC = HDR[KMAX]                    # 62
CKPT = 256                         # checkpoint distance

LAYERS = [ "rank1class8", "rank2class3", "rank2class4", "rank2class5",
    "rank2class6", "rank2class7", "rank3class2", "rank3class3", "rank3class4",
    "rank3class5", "rank3class6", "rank4class2", "rank4class3", "rank4class4",
    "rank4class5", "rank5class2", "rank5class3", "rank5class4", "rank6class2",
    "rank6class3", "rank7class2", "rank8class1" ]


def read_codes(path):
    with open(path) as f:
        txt = f.read()
    txt = txt.replace('\\\n', '')                 # GAP line continuations
    if ':=' in txt:
        txt = txt[txt.index(':=')+2 : txt.rindex(']')]
    return [int(x) for x in re.findall(r'\d+', txt)]


def code_to_exps(code):
    mask = code & ((1 << NREL) - 1)
    rest = code >> NREL
    exps = []
    for r in range(NREL):
        if (mask >> r) & 1:
            w = rest % SIZE
            rest //= SIZE
        else:
            w = 0
        for i in reversed(range(NTRITS[r])):
            exps.append(w // P**i % P)
    assert rest == 0, "code does not fit 8 generators"
    return exps


def exps_to_code(exps):
    w = []
    at = 0
    for r in range(NREL):
        x = 0
        for _ in range(NTRITS[r]):
            x = P*x + exps[at]
            at += 1
        w.append(x)
    code = sum(1 << r for r in range(NREL) if w[r])
    base = 1 << NREL
    for r in range(NREL):
        if w[r]:
            code += base * w[r]
            base *= SIZE
    return code


def encode(codes):
    rows = [code_to_exps(c) for c in codes]
    var = [p for p in range(NPOS) if len(set(row[p] for row in rows)) > 1]
    assert len(var) <= len(ALPHA), "too many varying positions"
    slot = {p: i for i, p in enumerate(var)}

    out = []
    ckpos, ckstate = [], []
    for n in range(1, len(rows)):
        if n % CKPT == 0:
            ckpos.append(len(out))
            ckstate.append(''.join(map(str, rows[n-1])))
        prev, row = rows[n-1], rows[n]
        ch = [p for p in var if row[p] != prev[p]]
        inc = [(row[p] - prev[p]) % P for p in ch]
        if len(ch) <= KMAX:
            out.append(HDR[len(ch)-1] + sum((d-1) << i for i, d in enumerate(inc)))
            out.extend(slot[p] for p in ch)
        else:
            out += [ESC, len(ch)]
            for p, d in zip(ch, inc):
                out += [slot[p], d-1]
    return dict(n=len(rows), base=''.join(map(str, rows[0])), var=var,
                ckpos=ckpos, ckstate=ckstate,
                data=''.join(ALPHA[s] for s in out))


def write(path, j, r):
    with open(path, 'w') as f:
        f.write('#\n# The groups of order 3^8 of rank %s and 3-class %s.\n'
                '# Generated by etc/encode-3hoch8.py; see lib/3hoch8/decode.g.\n#\n'
                % tuple(re.findall(r'\d+', os.path.basename(path))))
        f.write('SGLPPOW_3HOCH8_LAYER( %d, %d,\n"%s",\n[%s],\n[%s],\n[%s],\n'
                % (j, r['n'], r['base'],
                   ','.join(str(p+1) for p in r['var']),
                   ','.join(map(str, r['ckpos'])),
                   ',\n'.join('"%s"' % s for s in r['ckstate'])))
        # one line: a line break inside the data costs gzip about a quarter
        f.write('"%s" );\n' % r['data'])


def main(outdir, paths):
    total = 0
    for path in paths:
        name = os.path.basename(path)
        j = LAYERS.index(name) + 1
        codes = read_codes(path)
        r = encode(codes)
        assert decode(r) == codes, "%s: does not decode to its input" % name
        out = os.path.join(outdir, name)
        write(out, j, r)
        total += os.path.getsize(out)
        print("%-14s %7d groups %9d bytes" % (name, r['n'], os.path.getsize(out)))
    print("%-14s %25d bytes" % ("total", total))


def decode(r):
    """The inverse of encode, mirroring lib/3hoch8/decode.g."""
    sym = {c: i for i, c in enumerate(ALPHA)}
    state = [int(c) for c in r['base']]
    codes = [exps_to_code(state)]
    at = 0
    for n in range(1, r['n']):
        h = sym[r['data'][at]]
        at += 1
        if h == ESC:
            k = sym[r['data'][at]]
            at += 1
            ch = [(sym[r['data'][at+2*i]], sym[r['data'][at+2*i+1]] + 1)
                  for i in range(k)]
            at += 2*k
        else:
            k = next(i for i in range(1, KMAX+1) if h < HDR[i])
            h -= HDR[k-1]
            ch = [(sym[r['data'][at+i]], (h >> i) % 2 + 1) for i in range(k)]
            at += k
        for s, d in ch:
            state[r['var'][s]] = (state[r['var'][s]] + d) % P
        codes.append(exps_to_code(state))
    return codes


if __name__ == '__main__':
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2:])
